### PR TITLE
A theme integrated aproach

### PR DESCRIPTION
**Pull request by felipecrp**
This version use theme like colors.

### CODE REVIEW

**Comment by felipecrp** [comment]
Can you help fix text? I just changed colors.

**Comment by richrace** [comment]
Sure. I'll have a look tonight.

**Comment by richrace** [comment]
I've fixed the tests on master so if you merge in master or rebase your specs will be green.

However, I think this should be an option as with the current theme and syntax I'm using (One Dark for both) the highlight is pretty much no existent.

**Comment by felipecrp** [comment]
Nice. Tks. 

@richrace may it be because of the opacity?

**Pull request closed without merging**
